### ISSUE TITLE
User Story: Set up poll

### ISSUE THREAD

**Issue by G-Milzink** [G-Milzink/love-sandwiches#3]
As a **site administrator**, I can **put up a poll** so that **I can receive feedback from users**

## Acceptance Criteria:

- Polls can be set up quickly.
- Polls should be clearly vissible on the main page.

## Tasks:

- [ ] Fit poll section into main page design.
- [ ] Create standard poll template.
- [ ] Create administrator face for posting polls.
