### ISSUE TITLE
User Story: Review previous poll results.

### ISSUE THREAD

**Issue by G-Milzink** [G-Milzink/love-sandwiches#5]
As a **site administrator**, I can **review results of previous polls** so that **I can track changes in results over time.**

## Acceptance Criteria:

- Poll results can be stored.
- Stored results can be removed.
- Older poll results can be recalled.

## Tasks:

- [ ] Implement saving poll results.
- [ ] Implement deleting poll results.
- [ ] Implement poll overview section to display previous polls.
